### PR TITLE
context can be 1 or bigger

### PR DESCRIPTION
**Pull request by AdamRussak**
added >= to  if len(kc.config.Contexts) >= 1, as it could be a user has just 1 context in current file

### CODE REVIEW

**Comment by sunny0826** [comment]
@AdamRussak The `kc.config.Contexts` is only used to rename Contexts when there are multiple contexts in them (rule: filename + Hash of context) and does not affect multiple contexts being added to kubeconfig.

You can see the exact effect in the output of the [e2e test](https://github.com/sunny0826/kubecm/actions/runs/4271976146/jobs/7470825707).

**Comment by AdamRussak** [comment]
The fix addresses a scenario of a single context in the file.
It shouldn't be renamed, but it will.

I will go over the test and try to show it.

P.s
G8t project!

**Comment by sunny0826** [comment]
To cope with the problem of duplicate context names, the context is renamed each time it is added.

This is indeed a problem and is discussed in #602, but I haven't had time to address it so far.

**Comment by AdamRussak** [comment]
i overcame it in my implementation.
Will look for the time to contribute to your project.
But will need assistance with the testing part.

**Comment by sunny0826** [comment]
I will help you

**Comment by AdamRussak** [comment]
@sunny0826  please take a look (only) at the latest test run.
*here are the older once if you want to see: https://github.com/AdamRussak/kubecm/actions/workflows/e2e-test.yaml

some explanation:
in cmd/add.go line 119:
```go
if len(kc.config.Contexts) > 1 {
			newName = fmt.Sprintf("%s-%s", kc.fileName, HashSufString(name))
		} else {
			newName = name
		}
```
I replaced the `newName ` from `kc.filename` with just `name`.
the logic behind it is that it will keep the current context name of the cluster AS IS and will validate duplication in the following step.
I updated the context name for the switch test in the E2E pipeline to reflect that  name as it shows in the output: 
https://github.com/AdamRussak/kubecm/actions/runs/4419494196/jobs/7747985147#step:10:109


this should also resolve issue #602

**Review by sunny0826 — CHANGES_REQUESTED** [review]
It seems that this PR does not trigger the e2e test

**Comment by sunny0826** [comment]
> It seems that this PR does not trigger the e2e test

Oh, it worked

**Comment by AdamRussak** [comment]
@sunny0826  i see you requested some changes, but I cant see what changes you requested.

**Comment by sunny0826** [comment]
> @sunny0826 i see you requested some changes, but I cant see what changes you requested.

Sorry, I'm just waiting for the e2e test to finish running.

**Comment by sunny0826** [comment]
LGTM
Thanks for your contribution!

**Review by sunny0826 — APPROVED** [review]

**Pull request merged**
