### PR TITLE
feat: Refactor Azure support

### PR DESCRIPTION
**Pull request by jkroepke**
This PR overhaul the Azure support.

1. Adding Account field to ClusterInfo
2. Switch away from deprecated Azure SDKs
3. Implement SDK Auth type (this allows to authenticate with local azure cli.)
4. Choice between Admin KubeConfig (client cert) and User KubeConfig (SSO Login).
5. Remove Subscription Selector. List and Add command works across multiple subscriptions.
6. Use real ResourceID as ID inside kubecm

### CODE REVIEW

**Comment by sunny0826** [comment]
Thank you for your contribution. Since there are currently no unit test cases for Azure, I can't guarantee that this PR will work correctly. So I won't merge this PR for now, can you provide some screenshots of it when it runs correctly?

**Comment by sunny0826** [comment]
Otherwise, need to wait until I have time to do some manual testing to make sure he's running correctly.

**Comment by jkroepke** [comment]
I can do it at the new year, mid january

**Comment by jkroepke** [comment]
@sunny0826 I did a rebase, here are some pics.

<details>
<summary>Select Cloud</summary>

Bildschirmfoto 2024-02-11 um 19 33 39

</details>

<details>
<summary>Select Credentials</summary>

Bildschirmfoto 2024-02-11 um 19 33 46

</details>

<details>
<summary>List clusters</summary>

Bildschirmfoto 2024-02-11 um 20 02 50

</details>

<details>
<summary>Add clusters</summary>

Bildschirmfoto 2024-02-11 um 20 06 52

</details>

<details>
<summary>Select config type</summary>

Bildschirmfoto 2024-02-11 um 20 08 41

</details>

<details>
<summary>Confirm</summary>

Bildschirmfoto 2024-02-11 um 20 10 42

</details>

<details>
<summary>Summary</summary>

Bildschirmfoto 2024-02-11 um 20 11 13

</details>

**Comment by jkroepke** [comment]
Only the ID are problematic, because there are really, really only compared to AWS, making the cloud list table near to unreadable. In the secreenshot, I use a very small font size.

If possible, I would like to hide the ID colum and use it as internal value exclusivly for Azure.

**Review by sunny0826 — APPROVED** [review]
🎉 **LGTM**, Thanks for your contribute !

**Comment by sunny0826** [comment]
@all-contributors please add @jkroepke  for code

**Comment by jkroepke** [comment]
Great, thanks! Looking forward for the next release!

**Pull request merged**
