### PR TITLE
add KUBECM_DISABLE_K8S_MORE_INFO env to disable output moreinfo

### PR DESCRIPTION
**Pull request by yxxhero**
## Related Issue

resolves https://github.com/sunny0826/kubecm/issues/972

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes only affecting documentation)

## Checklist

- [x] I have tested my changes locally and ensured they are functioning properly.  Please run the `make build` and `make test` commands.
- [ ] I have added/updated unit or e2e tests to cover my changes.
- [ ] I have updated the relevant documentation. If you change commands or arguments, run `make doc-gen` to generate new documentation.

### CODE REVIEW

**Comment by yxxhero** [comment]
@sunny0826 WTDY? I am yuanXiongXiong.

**Review by sunny0826 — CHANGES_REQUESTED** [review]
Please add a description of this environment variable to `listExample()`.

**Review by sunny0826 — APPROVED** [review]
LGTM
Thank you for your valuable contribution to this project! Your work is greatly appreciated. 🎆

**Comment by sunny0826** [comment]
@all-contributors please add @yxxhero  for code

**Pull request merged**
